services:
  caddy:
    image: caddy:2-alpine
    ports:
      - "${HTTP_PORT:-0}:80"
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    restart: always
  
  web: &web-config
    image: ${WEB_IMAGE}
    expose:
      - "80"
    restart: always
  
  web-replica: *web-config
  
  backend: &backend-config
    image: ${BACKEND_IMAGE}
    expose:
      - "5000"
    environment:
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
      AES_KEY: ${AES_KEY}
      AES_IV: ${AES_IV}
      SHA256_KEY: ${SHA256_KEY}
      # This is the path to the volume mounted to /data in the container
      DataDir: /data
    volumes:
      - ${APPSETTINGS_PATH}:/app/appsettings.Production.json:ro
      - ${REFNOTES_CONFIG}:/root/.config/refnotes
      - ${REFNOTES_DATA_DIR}:/data
    restart: on-failure:3
    extra_hosts:
      - "host.docker.internal:host-gateway"

  backend-replica: *backend-config
  
  migrations:
    image: ${MIGRATIONS_IMAGE}
    volumes: 
      - ${APPSETTINGS_PATH}:/app/appsettings.Production.json:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes: !override
  caddy-data:
  caddy-config:
