services:
  caddy:
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
    restart: always
    networks:
      - internal

  backend: &backend-config
    volumes:
      - ${REFNOTES_CONFIG}:/root/.config/refnotes
      - ${REFNOTES_DATA_DIR}:/data
        
  backend-replica: *backend-config

  mysql-db:
    ports: !override [ ]
    expose:
      - "3306"
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql

volumes: !override
  caddy-data:
  caddy-config:
  scheduler-mysql-data:

networks:
  internal:
