services:
  caddy:
    image: caddy:2-alpine
    ports:
      - "${HTTP_PORT:-0}:80"
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - web
      - backend
    restart: always
    networks:
      - internal

  web:
    build: 
      context: .
      dockerfile: ./docker/web/Dockerfile
    image: angular-app
    expose:
      - "80"
    restart: always
    networks:
      - internal

  backend:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    expose:
      - "5000"
    env_file: .env
    depends_on:
      mysql-db:
        condition: service_healthy
      scheduler-db:
        condition: service_healthy
    volumes:
      - ${REFNOTES_CONFIG:-./}:/root/.config/refnotes
      - refnotes-data:/data
    restart: on-failure:3
    extra_hosts: 
      - "host.docker.internal:host-gateway"
    networks:
      - internal
  
  migrations:
    build:
      context: .
      dockerfile: ./docker/migrationservice/Dockerfile
    env_file: .env
    depends_on:
      mysql-db:
        condition: service_healthy
      scheduler-db:
        condition: service_healthy
    networks:
      - internal

  mysql-db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-refnotes}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
    ports:
      - "${DB_EXPOSE_PORT:-0}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  scheduler-db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: scheduler 
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_SCHEDULER:-root}
    ports:
      - "${DB_EXPOSE_PORT_SCHEDULER:-0}:3306"
    volumes:
      - scheduler-mysql-data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal


  redis:
    image: redis:8.0.3-alpine
    networks:
      - internal

volumes:
  mysql-data:
  scheduler-mysql-data:
  caddy-data:
  caddy-config:
  refnotes-data:

networks:
  internal:
