services:
  caddy:
    volumes:
      - ${CADDYFILE_PATH:-./docker/Caddyfile}:/etc/caddy/Caddyfile
    restart: always
    networks:
      - internal

  backend:
    volumes:
      - ${REFNOTES_CONFIG}:/root/.config/refnotes
      - ${REFNOTES_DATA_DIR}:/data

  mysql-db:
    ports: !override []
    expose:
      - "3306"
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql

volumes: !override
  caddy-data:
  caddy-config:

networks:
  internal:
