services:
  caddy:
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
    restart: always
    networks:
      - internal

  web: &web-config
    image: ${WEB_IMAGE}
    build: !override [ ]

  web-replica: *web-config

  backend: &backend-config
    image: ${BACKEND_IMAGE}
    build: !override [ ]
    volumes:
      - ${REFNOTES_CONFIG}:/root/.config/refnotes
      - ${REFNOTES_DATA_DIR}:/data

  backend-replica: *backend-config
  
  migrations:
    image: ${MIGRATIONS_IMAGE}
    build: !override [ ]

  mysql-db:
    ports: !override [ ]
    expose:
      - "3306"
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql

volumes: !override
  caddy-data:
  caddy-config:
  scheduler-mysql-data:

networks:
  internal:
