name: Build and Push Docker Images
permissions:
  contents: read
  packages: write
  pull-requests: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    
env:
  API_IMAGE: ghcr.io/${{ secrets.GHCR_REPOSITORY }}/refnotes-api
  MIGRATIONS_IMAGE: ghcr.io/${{ secrets.GHCR_REPOSITORY }}/refnotes-migrations
  WEB_IMAGE: ghcr.io/${{ secrets.GHCR_REPOSITORY }}/refnotes-web

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Api Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/api/Dockerfile
          push: true
          tags: ${{ env.API_IMAGE }}:latest,${{ env.API_IMAGE }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.API_IMAGE }}:latest
          cache-to: type=inline

      - name: Build and Push Migrations Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/migrationservice/Dockerfile
          push: true
          tags: ${{ env.MIGRATIONS_IMAGE }}:latest,${{ env.MIGRATIONS_IMAGE }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.MIGRATIONS_IMAGE }}:latest
          cache-to: type=inline

      - name: Build and Push Web Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/web/Dockerfile
          push: true
          tags: ${{ env.WEB_IMAGE }}:latest,${{ env.WEB_IMAGE }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.WEB_IMAGE }}:latest
          cache-to: type=inline
          build-args: |
            WEB_DOMAIN=${{ vars.WEB_DOMAIN }}
            WEB_URL=${{ vars.WEB_URL }}
