# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore Server/Server.csproj
      - name: Build
        run: dotnet build --no-restore Server/Server.csproj
      - name: Restore test dependencies
        run: dotnet restore ServerTests/ServerTests.csproj
      - name: Build tests
        run: dotnet build --no-restore ServerTests/ServerTests.csproj
      - name: Test
        run: dotnet test --no-build --verbosity normal --logger trx --results-directory "TestResults" ServerTests/ServerTests.csproj
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-results-8.0.x
          path: TestResults
        if: ${{ always() }}
