name: Angular
permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/Web/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/Web

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: './src/Web/pnpm-lock.yaml'
      - name: Install dependencies
        run: pnpm install
      - name: Run linting
        run: pnpm run lint
  
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/Web

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: './src/Web/pnpm-lock.yaml'
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm run test:ci


